Repository SchweizerischeBundesbahnen/scion-workbench, pull requests merged in 2019-07, with the labels that each got.

#157 fix: observe element dimension changes natively
  package.json
  projects/scion/dimension/src/lib/dimension.directive.ts
  projects/scion/dimension/src/lib/dimension.service.spec.ts
  projects/scion/dimension/src/lib/dimension.service.ts
  projects/scion/dimension/src/lib/mutation.service.ts
  projects/scion/dimension/src/public_api.ts
  projects/scion/dimension/tslint.json
  projects/scion/viewport/src/lib/scrollbar/scrollbar.component.html
  projects/scion/viewport/src/lib/scrollbar/scrollbar.component.scss
  projects/scion/viewport/src/lib/scrollbar/scrollbar.component.ts
  projects/scion/viewport/src/lib/viewport.component.html
  projects/scion/viewport/src/lib/viewport.component.scss
  projects/scion/viewport/src/lib/viewport.component.spec.ts
  projects/scion/viewport/src/lib/viewport.component.ts
  projects/scion/viewport/tslint.json
  projects/scion/workbench/src/lib/view-part/view-list/view-list.component.scss
  projects/scion/workbench/src/lib/view-part/view-part-bar/view-part-bar.component.html
  projects/scion/workbench/src/lib/view-part/view-part-bar/view-part-bar.component.ts
Labels: Breaking Change, bug

#75 feat: view tab activation history
  projects/e2e/workbench/src/view-tab-bar.e2e-spec.ts
  projects/scion/workbench-application-platform/src/lib/spec/manifest-collector.spec.ts
  projects/scion/workbench-application-platform/src/lib/spec/workbench-application-platform.module.spec.ts
  projects/scion/workbench/src/lib/spec/activities-from-lazy-loaded-modules.spec.ts
  projects/scion/workbench/src/lib/spec/activity-action.spec.ts
  projects/scion/workbench/src/lib/spec/activity-guard.spec.ts
  projects/scion/workbench/src/lib/spec/activity.spec.ts
  projects/scion/workbench/src/lib/spec/lazy-loaded-view-injection.spec.ts
  projects/scion/workbench/src/lib/spec/route-resolve.spec.ts
  projects/scion/workbench/src/lib/spec/router-navigate.spec.ts
  projects/scion/workbench/src/lib/spec/view-part-grid.component.spec.ts
  projects/scion/workbench/src/lib/spec/view-part-grid.spec.ts
  projects/scion/workbench/src/lib/spec/view.component.spec.ts
  projects/scion/workbench/src/lib/spec/views-from-lazy-loaded-modules.spec.ts
  projects/scion/workbench/src/lib/spec/wb-route-reuse-strategy.spec.ts
  projects/scion/workbench/src/lib/spec/workbench-testing.module.ts
  projects/scion/workbench/src/lib/view-activation-instant-provider.service.ts
  projects/scion/workbench/src/lib/view-part-grid/view-part-grid.model.ts
  projects/scion/workbench/src/lib/workbench-url-observer.service.ts
  projects/scion/workbench/src/lib/workbench-view-registry.service.ts
  projects/scion/workbench/src/lib/workbench.model.ts
  projects/scion/workbench/src/lib/workbench.module.ts
  projects/scion/workbench/src/public_api.ts
Labels: comp: workbench

#162 release: version 0.0.0-beta.25
  CONTRIBUTING.md
  package-lock.json
  package.json
  projects/app/common/package.json
  projects/scion/dimension/package.json
  projects/scion/mouse-dispatcher/package.json
  projects/scion/viewport/package.json
  projects/scion/workbench-application-platform.api/package.json
  projects/scion/workbench-application-platform/package.json
  projects/scion/workbench-application.angular/package.json
  projects/scion/workbench-application.core/package.json
  projects/scion/workbench/package.json
  resources/site/changelog.md
Labels: release
